"""Generator script for notebooks/colab_tqc_benchmark.ipynb."""

import json
import os
from pathlib import Path


def create_colab_notebook(output_path: str = "notebooks/colab_tqc_benchmark.ipynb") -> None:
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    cells = [
        # Cell 1: Header Markdown
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# TQC MuJoCo Benchmark Training (ICML 2020) - Google Colab GPU\n",
                "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/aryanthepain/RL_project/blob/main/notebooks/colab_tqc_benchmark.ipynb)\n",
                "\n",
                "Complete, automated reproduction harness for **Truncated Quantile Critics (TQC)** on Google Colab free GPUs.\n",
                "\n",
                "### Features Included:\n",
                "- **Tier 2 Compute Integration**: Headless EGL rendering (`MUJOCO_GL=egl`) to avoid GLFW context crashes.\n",
                "- **Storage Resilience**: Auto-mounting Google Drive with defensive directory auto-recreation on folder deletion.\n",
                "- **Auto-Resumption**: Seamlessly resumes from latest checkpoint across Colab session disconnections.\n",
                "- **Interactive Form Widgets**: Dropdown environment selection (`HalfCheetah`, `Hopper`, `Walker2d`, `Ant`, `Humanoid`) and presets (`smoke`, `quick`, `full`).\n",
                "- **Inactivity-Truncated Video Playback**: In-notebook HTML5 video player with Phase 7 adaptive inactivity truncation.\n",
                "- **Disk Quota Pruning**: In-notebook invocation of `clean_runs.py` to prevent filling Drive limits.\n",
                "- **One-Click Export**: Browser download of bundled `.tar.gz` run artifacts for non-Drive sessions.\n",
            ],
        },
        # Cell 2: Setup Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 1. Environment & GPU Pre-Flight Setup\n",
                "import os\n",
                "import sys\n",
                "\n",
                "# Configure Headless EGL rendering for MuJoCo on Colab GPU (D-12)\n",
                "os.environ[\"MUJOCO_GL\"] = \"egl\"\n",
                "\n",
                "# Install Linux packages required for headless rendering and video encoding\n",
                "!apt-get update -qq && apt-get install -y -qq libglew-dev patchelf ffmpeg > /dev/null\n",
                "\n",
                "import torch\n",
                "print(f\"PyTorch Version : {torch.__version__}\")\n",
                "print(f\"CUDA Available  : {torch.cuda.is_available()}\")\n",
                "if torch.cuda.is_available():\n",
                "    print(f\"GPU Device      : {torch.cuda.get_device_name(0)}\")\n",
                "    vram = torch.cuda.get_device_properties(0).total_memory / (1024**3)\n",
                "    print(f\"VRAM Available  : {vram:.2f} GB\")\n",
                "else:\n",
                "    print(\"Warning: Running on CPU runtime. Switch to GPU: Runtime -> Change runtime type -> T4 GPU.\")\n",
            ],
        },
        # Cell 3: Repo clone Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 2. Repository Cloning & Editable Installation\n",
                "import os\n",
                "import sys\n",
                "\n",
                "REPO_DIR = \"/content/RL_project\"\n",
                "BRANCH = \"gsd/phase-08-multi-tier-compute-hierarchy-and-google-colab-integration\"\n",
                "\n",
                "if not os.path.exists(REPO_DIR):\n",
                "    !git clone --branch {BRANCH} https://github.com/aryanthepain/RL_project.git {REPO_DIR}\n",
                "    %cd {REPO_DIR}\n",
                "else:\n",
                "    %cd {REPO_DIR}\n",
                "    !git pull\n",
                "\n",
                "# Install project in editable mode\n",
                "!pip install -q -e .\n",
                "\n",
                "# 1-second MuJoCo sanity check\n",
                "import gymnasium as gym\n",
                "env = gym.make(\"HalfCheetah-v4\")\n",
                "obs, _ = env.reset()\n",
                "assert obs is not None, \"Environment reset failed\"\n",
                "env.close()\n",
                "print(\"MuJoCo environment harness verified successfully!\")\n",
            ],
        },
        # Cell 4: Drive mount Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 3. Google Drive Persistence & Crash-Resilient Mount\n",
                "#@markdown Mount Google Drive to persist checkpoints across session timeouts.\n",
                "import os\n",
                "\n",
                "USE_GOOGLE_DRIVE = True #@param {type:\"boolean\"}\n",
                "DRIVE_RUNS_DIR = \"/content/drive/MyDrive/tqc_runs\"\n",
                "LOCAL_RUNS_DIR = \"/content/RL_project/runs\"\n",
                "\n",
                "if USE_GOOGLE_DRIVE:\n",
                "    try:\n",
                "        from google.colab import drive\n",
                "        drive.mount(\"/content/drive\")\n",
                "        os.makedirs(DRIVE_RUNS_DIR, exist_ok=True)\n",
                "        active_log_dir = DRIVE_RUNS_DIR\n",
                "        print(f\"Google Drive mounted. Checkpoints will be saved to: {active_log_dir}\")\n",
                "    except Exception as e:\n",
                "        print(f\"Drive mount failed or skipped ({e}). Falling back to local storage: {LOCAL_RUNS_DIR}\")\n",
                "        os.makedirs(LOCAL_RUNS_DIR, exist_ok=True)\n",
                "        active_log_dir = LOCAL_RUNS_DIR\n",
                "else:\n",
                "    os.makedirs(LOCAL_RUNS_DIR, exist_ok=True)\n",
                "    active_log_dir = LOCAL_RUNS_DIR\n",
                "    print(f\"Using local run directory: {active_log_dir}\")\n",
            ],
        },
        # Cell 5: Form widgets Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 4. Benchmark Experiment Configuration\n",
                "#@markdown Select environment, workload preset, and random seed.\n",
                "\n",
                "ENVIRONMENT = \"HalfCheetah-v4\" #@param [\"HalfCheetah-v4\", \"Hopper-v4\", \"Walker2d-v4\", \"Ant-v4\", \"Humanoid-v4\"]\n",
                "PRESET = \"quick\" #@param [\"smoke\", \"quick\", \"full\"]\n",
                "SEED = 42 #@param {type:\"integer\"}\n",
                "AUTO_RESUME = True #@param {type:\"boolean\"}\n",
                "\n",
                "from src.tqc.compute.dispatcher import ComputeDispatcher, get_preset_params\n",
                "from src.tqc.compute.tier_detector import TierDetector\n",
                "\n",
                "detector = TierDetector()\n",
                "dispatcher = ComputeDispatcher(detector=detector)\n",
                "print(detector.format_summary_table())\n",
                "params = get_preset_params(PRESET, ENVIRONMENT)\n",
                "print(f\"\\nConfigured Workload: {PRESET} on {ENVIRONMENT} ({params['timesteps']:,} steps)\")\n",
            ],
        },
        # Cell 6: Training Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 5. Execute Training with Checkpoint Resumption & Drive Resilience\n",
                "import torch\n",
                "from src.tqc.train import train_tqc\n",
                "\n",
                "device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
                "print(f\"Starting TQC training on device={device}...\")\n",
                "\n",
                "agent = train_tqc(\n",
                "    env_id=ENVIRONMENT,\n",
                "    seed=SEED,\n",
                "    total_timesteps=params[\"timesteps\"],\n",
                "    eval_freq=params[\"eval_freq\"],\n",
                "    eval_episodes=params[\"eval_episodes\"],\n",
                "    warmup_steps=params[\"warmup_steps\"],\n",
                "    batch_size=params[\"batch_size\"],\n",
                "    buffer_capacity=params[\"buffer_capacity\"],\n",
                "    device=device,\n",
                "    log_dir=active_log_dir,\n",
                "    checkpoint_freq=params[\"checkpoint_freq\"],\n",
                "    resume=AUTO_RESUME,\n",
                ")\n",
                "print(\"Training execution finished successfully!\")\n",
            ],
        },
        # Cell 7: Plotting Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 6. Live Metrics Visualization\n",
                "import glob\n",
                "import os\n",
                "import matplotlib.pyplot as plt\n",
                "import pandas as pd\n",
                "\n",
                "# Locate metrics.csv in active run directory\n",
                "metric_files = sorted(glob.glob(f\"{active_log_dir}/**/metrics.csv\", recursive=True), key=os.path.getmtime, reverse=True)\n",
                "\n",
                "if metric_files:\n",
                "    latest_metrics = metric_files[0]\n",
                "    print(f\"Plotting metrics from: {latest_metrics}\")\n",
                "    df = pd.read_csv(latest_metrics)\n",
                "\n",
                "    fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
                "    \n",
                "    if \"eval_return_mean\" in df.columns:\n",
                "        axes[0].plot(df[\"step\"], df[\"eval_return_mean\"], label=\"Eval Return\", color=\"#2563eb\", lw=2)\n",
                "        if \"eval_return_std\" in df.columns:\n",
                "            axes[0].fill_between(df[\"step\"], df[\"eval_return_mean\"] - df[\"eval_return_std\"], df[\"eval_return_mean\"] + df[\"eval_return_std\"], alpha=0.2, color=\"#2563eb\")\n",
                "        axes[0].set_title(f\"{ENVIRONMENT} - Evaluation Return\")\n",
                "        axes[0].set_xlabel(\"Environment Steps\")\n",
                "        axes[0].set_ylabel(\"Average Return\")\n",
                "        axes[0].grid(True, alpha=0.3)\n",
                "        axes[0].legend()\n",
                "\n",
                "    if \"critic_loss\" in df.columns:\n",
                "        axes[1].plot(df[\"step\"], df[\"critic_loss\"], label=\"Critic Loss\", color=\"#dc2626\", lw=1.5)\n",
                "        axes[1].set_title(\"Quantile Critic Loss\")\n",
                "        axes[1].set_xlabel(\"Environment Steps\")\n",
                "        axes[1].grid(True, alpha=0.3)\n",
                "        axes[1].legend()\n",
                "\n",
                "    if \"alpha\" in df.columns:\n",
                "        axes[2].plot(df[\"step\"], df[\"alpha\"], label=\"Temperature (alpha)\", color=\"#16a34a\", lw=1.5)\n",
                "        axes[2].set_title(\"Entropy Temperature\")\n",
                "        axes[2].set_xlabel(\"Environment Steps\")\n",
                "        axes[2].grid(True, alpha=0.3)\n",
                "        axes[2].legend()\n",
                "\n",
                "    plt.tight_layout()\n",
                "    plt.show()\n",
                "else:\n",
                "    print(f\"No metrics.csv found in {active_log_dir}.\")\n",
            ],
        },
        # Cell 8: Video Player Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 7. In-Notebook Video Playback with Inactivity Truncation\n",
                "import glob\n",
                "import os\n",
                "from IPython.display import HTML, Video, display\n",
                "\n",
                "# Find latest best_model.pt or final_model.pt\n",
                "model_files = sorted(glob.glob(f\"{active_log_dir}/**/best_model.pt\", recursive=True), key=os.path.getmtime, reverse=True)\n",
                "if not model_files:\n",
                "    model_files = sorted(glob.glob(f\"{active_log_dir}/**/final_model.pt\", recursive=True), key=os.path.getmtime, reverse=True)\n",
                "\n",
                "if model_files:\n",
                "    ckpt_path = model_files[0]\n",
                "    out_video = \"/content/evaluation_video.mp4\"\n",
                "    print(f\"Rendering evaluation video from checkpoint: {ckpt_path}\")\n",
                "\n",
                "    # Invoke visualize.py with Phase 7 inactivity truncation\n",
                "    !python src/tqc/visualize.py --checkpoint {ckpt_path} --env {ENVIRONMENT} --output {out_video} --truncate-inactive --episodes 1\n",
                "\n",
                "    if os.path.exists(out_video):\n",
                "        print(f\"Displaying video: {out_video}\")\n",
                "        display(Video(out_video, embed=True, width=640))\n",
                "    else:\n",
                "        print(\"Video generation failed or output not found.\")\n",
                "else:\n",
                "    print(f\"No checkpoint found in {active_log_dir} to render video.\")\n",
            ],
        },
        # Cell 9: Quota Pruning Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 8. Disk Quota Inspection & Checkpoint Pruning\n",
                "#@markdown Inspect storage and prune intermediate checkpoints while preserving best_model and metrics.\n",
                "PRUNE_NOW = False #@param {type:\"boolean\"}\n",
                "DRY_RUN = True #@param {type:\"boolean\"}\n",
                "\n",
                "prune_flags = \"\"\n",
                "if PRUNE_NOW:\n",
                "    prune_flags += \"--prune \"\n",
                "    if DRY_RUN:\n",
                "        prune_flags += \"--dry-run \"\n",
                "    else:\n",
                "        prune_flags += \"--yes \"\n",
                "else:\n",
                "    prune_flags += \"--inspect \"\n",
                "\n",
                "!python scripts/clean_runs.py --dir {active_log_dir} {prune_flags}\n",
            ],
        },
        # Cell 10: Zip Export Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 9. Bundle and Download Artifacts (.tar.gz)\n",
                "#@markdown For sessions without Google Drive, export artifacts directly to browser.\n",
                "import os\n",
                "import tarfile\n",
                "try:\n",
                "    from google.colab import files\n",
                "    HAVE_COLAB = True\n",
                "except ImportError:\n",
                "    HAVE_COLAB = False\n",
                "\n",
                "tar_name = f\"tqc_{ENVIRONMENT}_artifacts.tar.gz\"\n",
                "print(f\"Creating archive {tar_name} from {active_log_dir}...\")\n",
                "\n",
                "with tarfile.open(tar_name, \"w:gz\") as tar:\n",
                "    tar.add(active_log_dir, arcname=os.path.basename(active_log_dir))\n",
                "\n",
                "print(f\"Archive ready ({os.path.getsize(tar_name) / (1024*1024):.2f} MB).\")\n",
                "if HAVE_COLAB:\n",
                "    try:\n",
                "        files.download(tar_name)\n",
                "    except Exception as e:\n",
                "        print(f\"Download trigger notice: {e}\")\n",
                "else:\n",
                "    print(f\"Archive saved locally: {os.path.abspath(tar_name)}\")\n",
            ],
        },
    ]

    notebook_data = {
        "cells": cells,
        "metadata": {
            "accelerator": "GPU",
            "colab": {
                "name": "colab_tqc_benchmark.ipynb",
                "provenance": [],
                "toc_visible": True,
            },
            "kernelspec": {
                "display_name": "Python 3",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 0,
    }

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(notebook_data, f, indent=1)

    print(f"Successfully generated {output_path} with {len(cells)} cells.")


if __name__ == "__main__":
    create_colab_notebook()
